/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFactoryContract,
  IFactoryContractInterface,
} from "../../../contracts/interfaces/IFactoryContract";

const _abi = [
  {
    inputs: [],
    name: "getPauseAllStatus",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFactoryContract__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryContractInterface {
    return new utils.Interface(_abi) as IFactoryContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFactoryContract {
    return new Contract(address, _abi, signerOrProvider) as IFactoryContract;
  }
}
