/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicNftSol from "./basic_nft.sol";
export type { basicNftSol };
import type * as basicTokenSol from "./basic_token.sol";
export type { basicTokenSol };
import type * as factoryContractSol from "./factory_contract.sol";
export type { factoryContractSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
